redis:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - ./deepdream:/data

compute:
  image: hamstah/deepdream-manager
  command: /bin/bash -c "cd /opt/manager/manager && rqworker -c rq_settings compute"
  volumes:
    - ./deepdream:/opt/deepdream
    - ./deepdream-manager/manager:/opt/manager
  links:
    - redis
  mem_limit: 1740M

manager:
  image: hamstah/deepdream-manager
  command: gunicorn manager:app --bind 0.0.0.0:8000 --reload --chdir /opt/manager
  volumes:
    - ./deepdream:/opt/deepdream
    - ./deepdream-manager/manager:/opt/manager
  links:
    - redis

nginx:
  image: nginx
  volumes:
    - ./deepdream:/opt/deepdream
    - ./deepdream/nginx.conf:/etc/nginx/nginx.conf
  links:
    - manager
  ports:
    - 80:80
